from . import receta_ficha
from . import articulos
from . import campliado
from . import cantidad
from . import codigosec
from . import compmanu
from . import componente
from . import copiaficha
from . import cunitario
from . import depto
from . import descripcion
from . import factperdida
from . import temporadas
from . import umedida